Add src layout structure
cobbler/cobbler-tftp pull request #9
Opened 2023-03-17 14:28 UTC by ByteOtter

Fixes #1, #2 

Introduce src-layout to the project alongside the necessary configuration files.

2023-03-17 14:54 UTC, SchoolGuy requested changes
`setup.cfg` has some old leftovers of the PoC. Let's change that please.

2023-03-20 19:19 UTC, SchoolGuy commented on setup.cfg
> +zip_safe = Frue
```suggestion
zip_safe = True
```

or 

```suggestion
zip_safe = False
```

2023-03-20 19:20 UTC, SchoolGuy commented on setup.cfg
> +author_email = christopher.hock@suse.com
```suggestion
author = Team Cobbler
author_email = cobbler.project@gmail.com
```

2023-03-20 19:20 UTC, SchoolGuy commented on setup.cfg
> +  importlib-resources~=5.12.0
There are some linters hiding in there.

2023-03-21 09:00 UTC, ByteOtter commented on setup.cfg
> +url = https://github.com/ByteOtter/cobbler-tftp
fixed 👍🏼

2023-03-21 09:01 UTC, ByteOtter commented on setup.cfg
> +zip_safe = Frue
opted for true for now 👍🏼

2023-03-21 09:02 UTC, ByteOtter commented on setup.cfg
> +  importlib-resources~=5.12.0
removed black from there and moved the extra dependencies into their own `[options.extras_require]` block

2023-03-21 09:14 UTC, SchoolGuy requested changes
I am sorry but the dependencies we name are not in a shape I feel confident where we can already merge this PR.

If you desire that we version lock all of our dependencies explicitly (it is a valid strategy after all) then I would like us to use [Poetry](https://python-poetry.org/). However, this is not needed for this project. Well-thought version constraints should be enough.

I am sorry if I have overlooked other dependencies that this project doesn't need but with the questions I have provided in the individual comments, we should already have a much leaner dependency tree.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  packaging~=23.0
This package requires Python 3.7 or greater and I doubt it is required for the runtime of the project.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  mypy-extensions~=1.0.0
This is just for typing. Are we sure we need that? Seems to me that with `pyright` this dependency is not required anymore.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  pip~=23.0.1
That for sure is not needed for running a tftp server IMHO. I can also not figure out why we need exactly this version for developing this project.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  pluggy~=1.0.0
I know that this is a dependency of `pytest`. I don't believe we will need it at this early stage of the project. If we need it please feel free to correct me.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  py~=1.11.0
This library is in [maintenance mode](https://pypi.org/project/py/). I am not aware why we would need that?

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  typing_extensions~=4.5.0
Is there a particular reason why we need this package?

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  tomli~=2.0.1
Do we need this as well? The config is in YAML and I am not aware of any TOML files we need to parse atm.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  sphinxcontrib-serializinghtml~=1.1.5
Those are dependencies of Sphinx itself I guess. Explicitly we don't need them afaik. Let's try to get rid of them.

2023-03-21 09:14 UTC, SchoolGuy commented on setup.cfg
> +  setuptools<=44.11.0
So I believe that we don't need something that is smaller or equal to 44.11.0. I believe that atm we should be able to install this project also with more modern versions of `setuptools`. So I believe we want this if I am not mistaken:

```suggestion
  setuptools>=44.11.0
```

2023-03-22 10:44 UTC, ByteOtter commented on setup.cfg
> +  tomli~=2.0.1
Most of these requirements like `tomli` are requirements of requirements. In this case this is a requirements of `setuptools-scm`. I'm currently looking up if we need to declare them and will clean them up accordingly

2023-03-27 08:36 UTC, ByteOtter commented
> I am sorry but the dependencies we name are not in a shape I feel confident where we can already merge this PR.
> 
> If you desire that we version lock all of our dependencies explicitly (it is a valid strategy after all) then I would like us to use [Poetry](https://python-poetry.org/). However, this is not needed for this project. Well-thought version constraints should be enough.
> 
> I am sorry if I have overlooked other dependencies that this project doesn't need but with the questions I have provided in the individual comments, we should already have a much leaner dependency tree.

Alright, newest update should fix all these concerns. I changed all dependency versions to their latest release which still supported Python 3.6 and removed all which are not explicitly needed.

2023-03-27 11:43 UTC, SchoolGuy reviewed
Looking much better! Two questions/open points are left.

2023-03-27 11:43 UTC, SchoolGuy commented on setup.cfg
> +  python_version>=3.6
Is this dependency here on purpose?

I see it mapping to this project: https://gitlab.com/halfak/python_version

2023-03-27 11:43 UTC, SchoolGuy commented on setup.cfg
> +  pip>=21.3.1
`pip` is not needed to run the project. This project doesn't integrate with `pip` and thus we can maybe open the `dev_requires` section for that but please let's remove that from the install_requires.

2023-03-27 11:57 UTC, ByteOtter commented on setup.cfg
> +  pip>=21.3.1
moved it to a new `dev_requires` section

2023-03-27 12:00 UTC, ByteOtter commented on setup.cfg
> +  python_version>=3.6
It shouldn't go there. I may have misinterpreted the (`setup.cfg Example`)[https://web.archive.org/web/20200118161529/https://setuptools.readthedocs.io/en/latest/setuptools.html#using-a-src-layout] in the old setuptools documentation and was led to believe I need to specify the exact python version in the `install_requires` section.

However, upon closer inspection it looks like I need to do so in the `classifiers` section with
```cfg
Programming Language :: Python :: 3.6
```

2023-03-27 13:48 UTC, SchoolGuy approved these changes
LGTM

2023-03-27 13:48 UTC, merged